### ISSUE TITLE
Segmentation Fault error

### ISSUE THREAD

**Issue by aegeavaz-pfizer** [wilsonzlin/minify-html#108]
Hi...

I'm having a problem trying to minify the html that I have in a database record. With other records are working fine.
It happens in an Amazon Linux 2 ec2 machine, but not in my ubuntu local machine.
You can find attached the html that is causing the error.

Thanks.
Regards.

[segmentation_fault.txt](https://github.com/wilsonzlin/minify-html/files/9423107/segmentation_fault.txt)
.

**Comment by wilsonzlin** [comment]
I'm unable to reproduce the issue on my machine either. If the input HTML document has a very deep tree (i.e. deeply nested tags), it may be possible that the segmentation fault is due to a too limited stack size limit, which may be more conservatively set on Amazon Linux 2. If the issue still persists, can you provide a core dump?
