### ISSUE TITLE
Build arm python wheels

### ISSUE THREAD

**Issue by zinootje** [wilsonzlin/minify-html#11]
Would it be possibly to build wheels for arm especially armv7  or provide instructions to build it

**Comment by wilsonzlin** [comment]
You can build it from source by cloning the repo and building the Python library from source in the `python` directory; it's a standard Rust project, so you can build using standard Rust tools, which should let you specify an ARM target. Before building from source, run `prebuild.sh` in the root directory; you will need Node.js installed.

Building for ARM as part of this project's pipeline might be tricky as [maturin](https://github.com/PyO3/maturin) is used for building and publishing wheels, and it doesn't appear to have good ARM support currently; I'll take a deeper look sometime.

**Comment by belinghy** [comment]
Sorry for commenting on an old thread.  I have been using minify-html for my project (thank you!).  I was devastated when I found out yesterday that it can't be installed via pip on my new macbook.  Thankfully I was able to build it from source by following the steps listed in Github actions. 

I didn't encounter any problem with maturin, so I think the problem might have been fixed in the newer releases?  Wondering if you could take a look again.  Having this package available via pip for new macs will be helpful for a lot of people!  Let me know if there is anything I can do to help.

**Comment by wilsonzlin** [comment]
I've added support for Python ARM64 on Linux and macOS in version `0.7.0`. If you try it out let me know how it goes.
