### ISSUE TITLE
minify-html does not respect whitespaces in <pre>

### ISSUE THREAD

**Issue by Keats** [wilsonzlin/minify-html#21]
For example:

```html
<pre style="background-color:#2b303b;">
    <code class="language-rust" data-lang="rust"><span style="color:#b48ead;">fn </span><span style="color:#8fa1b3;">main</span><span style="color:#c0c5ce;">() {
      println!(&quot;</span><span style="color:#a3be8c;">Hello, world!</span><span style="color:#c0c5ce;">&quot;);
    }
    </span></code></pre>
```

After `./target/debug/minify-html-cli --src test.html -o out.html`:

```html
<pre style=background-color:#2b303b;>
    <code class=language-rust data-lang=rust><span style=color:#b48ead;>fn </span><span style=color:#8fa1b3;>main</span><span style=color:#c0c5ce;>() { println!("</span><span style=color:#a3be8c;>Hello, world!</span><span style=color:#c0c5ce;>"); } </span></code></pre>
```

minify-html should not touch any whitespace inside `<pre>` since it's already formatted.

**Comment by flother** [comment]
I think this is due to the context-aware minification being reset when there's a child element within a  `<pre>` or `<code>` element. For example, this HTML:

```html
<pre><code>fn main() {
  println!("Hello, world!");
  loop {
    println!("Hello, world!");
  }
}
</code></pre>

<pre><code>fn main() {
  println!("Hello, world!");
  <span>loop {
    println!("Hello, world!");
  }</span>
}
</code></pre>
```

Is converted into this minified HTML:

```html
<pre><code>fn main() {
  println!("Hello, world!");
  loop {
    println!("Hello, world!");
  }
}
</code></pre><pre><code>fn main() {
  println!("Hello, world!");
  <span>loop { println!("Hello, world!"); }</span>
}
</code></pre>
```

The two code blocks are the same, except the second has a `<span>` child element. Within that element, all whitespace is collapsed. I think the solution is to keep the `<pre>` context-awareness unchanged when it has [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content) children.

**Comment by wilsonzlin** [comment]
Thanks for raising, I've updated the code to use `<pre>` whitespace minification rules (i.e. none) for all descendants of `<pre>`. Using the latest version `0.4.2`, the output is:

```html
<pre><code>fn main() {
  println!("Hello, world!");
  loop {
    println!("Hello, world!");
  }
}
</code></pre><pre><code>fn main() {
  println!("Hello, world!");
  <span>loop {
    println!("Hello, world!");
  }</span>
}
</code></pre>
```
