### ISSUE TITLE
Stripping quotes can end up producing invalid HTML

### ISSUE THREAD

**Issue by Keats** [wilsonzlin/minify-html#41]
See https://github.com/getzola/zola/issues/1511#issuecomment-892679811

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;500;800&display=swap">
```

gets minified to 

```html
<link rel=stylesheet href=https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;500;800&display=swap>
```

**Comment by wilsonzlin** [comment]
I just tested the output and it is still parsed correctly in browsers; to test, check the `.href` property of the corresponding DOM node. It may be invalid HTML, but this is not a requirement of minify-html as per the README:

> Note that many of the minification done can result in HTML that will not pass validation, but remain interpreted and rendered correctly by the browser; essentially, the laxness of the browser is taken advantage of for better minification.

In this case, there are two special rules:

- The [WHATWG spec](https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state) requires that named entity references in attribute values are not decoded if they do not end with a semicolon and are followed by an alphanumeric or `=` character (see #33).
- Browsers consider the end of an unquoted attribute value to be the first whitespace or `>` character, and so permits characters like `=`, despite the spec saying otherwise.

**Comment by wilsonzlin** [comment]
Just an update, I am currently developing the next version which will support turning off specific minification features, including non-standards compliant ones. It should be out within the next day or two. The feature has been requested a lot so it's worth developing.

**Comment by wilsonzlin** [comment]
This has been implemented as of version `0.5.3`. Unquoted attribute values can be enforced to follow the spec using `cfg.ensure_spec_compliant_unquoted_attribute_values`.

Note that `0.5.x` is a breaking change from `0.4.x`, but API changes are minor. For the Rust library, there is now only one function called `minify`. The library can now handle all inputs so the return value is always a `Vec<u8>`, not `Result` (i.e. there are no possible errors).

Let me know if it works for you.

**Comment by Keats** [comment]
Perfect thanks, I'll try it asap

**Comment by Keats** [comment]
It would be nice if `Cfg` was implementing `Default` so you can just do:
```
    let cfg = &Cfg {
        ensure_spec_compliant_unquoted_attribute_values: true,
        keep_spaces_between_attributes: true,
        ..Default::default()
    };
```
It would also be nice to have `Cfg::spec_compliant` that turns on the correct flags as a shortcut.
Otherwise it looks like it works fine!

**Comment by wilsonzlin** [comment]
Both are now available as of `0.6.7`.

**Comment by Keats** [comment]
Even with `keep_spaces_between_attributes`, it seems to now convert `<!doctype html>` to `<!doctypehtml>`. I *believe* it was not removing the space yesterday with 0.5?

**Comment by wilsonzlin** [comment]
Yes it was added recently. Version `0.6.8` now has a Cfg option to disable it. It's disabled when using `Cfg::spec_compliant`.
