### ISSUE TITLE
issues with x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by untoreh** [wilsonzlin/minify-html#79]
I tried building minify-html against the musl target and found some issues when the `esbuild` feature is enabled:
- rust debug builds always crash with "sigsev address boundary error"
- calling `sleep` anywhere inside the code (or from outside since I was linking to minify_html from nim) makes it crash, even on release builds.
I tested on glibc and these problems don't appear

**Comment by wilsonzlin** [comment]
I suspect the issue is with the use of Cgo and the Go runtime that comes bundled with esbuild, which seem to depend strongly on glibc. In the latest version `0.9.0`, esbuild has been replaced with [minify-js](https://github.com/wilsonzlin/minify-js), a JS minifier I wrote from scratch fully in Rust, so there should no longer be any issues similar to what you've described. Let me know if it works on your end.

If you've integrated minify-html with another language and it's an open source library, I'm happy to link to it in the README to let others know 😃
