### ISSUE TITLE
allow to pass custom whitespace sensitive tags

### ISSUE THREAD

**Issue by untoreh** [wilsonzlin/minify-html#84]
The only tags that are whitespace sensitive don't include something generic like `article`. 
An option to pass custom tags could be considered?

Using the `code` tag to wrap content is not ideal, while using `pre` with css `white-space: break-space` is ok, although confusing

**Comment by wilsonzlin** [comment]
I probably won't implement this as this would increase the complexity by a lot, due to how calling from other languages works (managing memory, ensuring pointer safety, dealing with Rust lifetimes, heap allocation, etc.), which would have to be done for every platform. There would also be a performance cost, since configuration data is no longer static. This is a trade off as the default rules are made with standard usages of HTML5 in mind according to the specs, so there may be disadvantages for a more rare and nonstandard input.
