### ISSUE TITLE
Allow configuration of `css-minify` level

### ISSUE THREAD

**Issue by fdemmer** [wilsonzlin/minify-html#89]
While css-minify provides three levels of optimization and [defaults to `1`](https://github.com/Mnwa/css-minify/blob/master/css-minify/Readme.md?plain=1#L57), minify-html hardcodes `Level::Three`.

This may cause problems when refining a CSS rule with overrides inline in HTML. 

My exact use-case is a general rule (in separate CSS file) with `background-position`, `background-size` and `background-image` with a default image, and a specific rule inline in HTML with only `background-image` declaration to set a specific image.

`Level::Three` optimization reduces the inline `background-image: url(...)` declaration to just `background: url(...)` which has precedence, so the general `-position` and `-size` properties are not used.

I know adding config args for every little detail is "painful", but maybe you agree that it's worth it for this :)

**Comment by wilsonzlin** [comment]
Thanks for raising this, I've replaced css-minify with lightningcss in version `0.13.0`, let me know if this issue still occurs.

Note that before changing to lightningcss, it has been possible to change the CSS optimisation level since [0.11.0](https://github.com/wilsonzlin/minify-html/blob/master/CHANGELOG.md#0110).
