### ISSUE TITLE
`minify_html = true` causes Major page formatting issues to pages with numbered code blocks in Zola.

### ISSUE THREAD

**Issue by Jieiku** [wilsonzlin/minify-html#96]
# Bug Report

`minify_html = true` causes Major page formatting issues to pages with numbered code blocks.

This was first reported to the abridge theme: https://github.com/Jieiku/abridge/issues/84

I then posted this to the zola issue tracker: https://github.com/getzola/zola/issues/1942 (I am now posting it all here for completeness sake)

I implemented this in the [after-dark theme](https://github.com/getzola/after-dark) and seen the same effect (pay particular attention to the footer at the bottom of the pages)

![2022-07-25_13-26-01](https://user-images.githubusercontent.com/106644/180867885-bea50ffb-fbc5-488f-a442-c8ce5538c204.png)

with `minify_html = false` it looks normal:

![2022-07-25_14-21-34](https://user-images.githubusercontent.com/106644/180876108-c8d988be-278e-4130-b6b2-090e44de3a4e.png)

## Environment

Zola version: 0.16.0

I also tested 0.15.3 with the same result.

## Expected Behavior

The page should look the same with or without `minify_html = true`

## Current Behavior
No Errors, just errors in page formatting when using `minify_html = true`

## Step to reproduce

```shell
git clone https://github.com/Jieiku/zola-minify-test
cd zola-minify-test
zola serve

```
open this page: http://127.0.0.1:1111/overview-code-blocks/

Notice the page section headings and page footer are all broken following the numbered code blocks.

To further confirm the issue you can removed the line numbered code blocks, then `minify_html = true` will no longer cause an issue.

**Comment by winstonewert** [comment]
The generate html contains several instances of:

`</td></tr></span></tbody></table></code>`

This attempts to close a span tag that was never opened. So html being fed into the minimizer is broken. Whatever the case for minify-html, that should be corrected.

Eliding all unneccessary details, a minimal test case looks something like this.

`<pre></span></pre>`

minify-html turns it into:

`<pre><span><pre>`

The rest of the page ends up being inside a `pre` tag which causes the weirdness.

**Comment by Jieiku** [comment]
So is this an issue with zola then?

**Comment by wilsonzlin** [comment]
Thanks for looking into this @winstonewert. It's not possible for minify-html to understand invalid HTML syntax by definition (nor is it its responsibility); @Jieiku if the HTML was generated, I'd suggest raising an issue with whatever tool generated the HTML.

With regards to the `<pre></span></pre>` test case, the behaviour was changed in version `0.10.0` (not yet released) to simply drop the invalid closing tag instead of reinterpreting it as an opening tag, as it avoids an explosion in the tree if there are many (e.g. broken HTML generator/template). For reference, how minify-html handles invalid input is described in [notes/Parsing.md](https://github.com/wilsonzlin/minify-html/blob/master/notes/Parsing.md) as mentioned in the README.

**Comment by Jieiku** [comment]
Thanks @wilsonzlin , There is a ticket open at zola, hopefully somebody can figure out the cause.
